name: Tests # 工作流名称

on:
  push:
    paths: 
      - '.github/**'
      # - 'projects/market/src/**' 
    #   - 'projects/market/test/**'
    branches:
      - dev # 当 main 分支有代码推送时触发工作流

jobs:
  market-test:
    name: market-test # 工作流名称123
    environment: base-sepolia
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY_BASE: ${{ secrets.ENVKEY_ETHERSCAN_API_KEY_BASE }}
      ETH_NODE_URI_BASE_SEPOLIA: ${{ secrets.ENVKEY_ETH_NODE_URI_BASE_SEPOLIA }}
      MNEMONIC: ${{ secrets.MNEMONIC }}
    
    steps:
      - uses: actions/checkout@v4

      # 设置 Node.js 环境
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x # 使用 Node.js 版本 20.x

      # 安装依赖
      - name: Install submodule
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: cd projects/market && yarn install --frozen-lockfile && cd ../.. # 安装依赖，确保锁定文件一致

      - name: typechain
        run: cd projects/market && yarn prepare && cd ../.. # 编译代码

      # 编译代码
      - name: Compile
        run: cd projects/market && yarn compile && cd ../.. # 编译代码
      
      # - name: test
      #   run: cd projects/market && yarn test && cd ../.. # 编译代码

      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          
      - run: git config --global user.email "zhuoqian.zhou@dalveytech.com"
      - run: git config --global user.name "CD Bot"
      - run: git remote set-url --push origin git@github.com:dalveytech-zhuoqian/contracts-v2-fork.git
      - run: cd projects/market && yarn deploy base_sepolia && git add projects/market/deployments/base_sepolia && git commit -m "Deploy contracts on base sepolia" && git push

