name: Tests # 工作流名称

on:
  push:
    branches:
      - dev # 当 main 分支有代码推送时触发工作流
  pull_request: # 当有 pull request 时触发工作流

jobs:
  unit-tests: # 作业名称
    name: Unit Tests # 作业显示名称
    runs-on: ubuntu-latest # 作业运行环境为最新的 Ubuntu

    steps: # 作业步骤
      # 检出代码
      - uses: actions/checkout@v4

      # 设置 Node.js 环境
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x # 使用 Node.js 版本 20.x

      # 缓存 Yarn 依赖
      - id: yarn-cache
        run: cd projects/market && echo "::set-output name=dir::$(yarn cache dir)" # 设置输出变量以缓存 Yarn 依赖目录

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }} # 缓存 Yarn 依赖目录
          key: yarn-${{ hashFiles('projects/market/yarn.lock') }} # 缓存键值，根据 yarn.lock 文件生成
          restore-keys: |
            yarn-  # 恢复缓存的键值

      # 安装依赖
      - name: Install dependencies
        run: cd projects/market && yarn install --frozen-lockfile # 安装依赖，确保锁定文件一致

      # 编译代码
      - name: Compile
        run: cd projects/market && yarn compile # 编译代码

      # 运行单元测试
      - name: Run unit tests
        run: cd projects/market && yarn test # 运行单元测试
