name: Tests # 工作流名称

on:
  push:
    branches:
      - dev # 当 main 分支有代码推送时触发工作流
  pull_request: # 当有 pull request 时触发工作流

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_10_A_NUMBERED_KEY: "lorem"
        envkey_3_ANOTHER_NUMBERED_KEY: "ipsum"
        envkey_5_NUMBERED_KEY_VALUE_WITH_SPACES: "lorem ipsum"
        envkey_1_ONE_MORE_NUMBERED_KEY: true
        jsonkey_VARKEY1: '[{"key": "VARKEY",	"value": "VARVALUE"}, {	"key": "VARKEY1",	"value": "VARVALUE1"}, {	"key": "VARKEY2",	"value": "VARVALUE2"}]'
        jsonkey_JVARKEYWITHALIAS: 'OVERRIDEKEY|[{"key": "JVARKEY",	"value": "VARVALUE"}, {"key": "OVERRIDEKEY",	"value": "VARVALUE"}, {	"key": "JVARKEY1",	"value": "VARVALUE1"}, {	"key": "JVARKEY2",	"value": "VARVALUE2"}, {	"key": "JVARKEYSPACE",	"value": "VAR KEY SPACE"}, {	"key": "JVARKEYVAR",	"value": "$VAR"}, {	"key": "JVARKEYLITERAL",	"value": "$VA%%%R"}]'
        some_other_variable: foobar
        directory: ./projects/market
        file_name: .env
        fail_on_empty: false

  unit-tests: # 作业名称
    name: Verify Contracts Base Sepolia # 作业显示名称
    runs-on: ubuntu-latest # 作业运行环境为最新的 Ubuntu

    steps: # 作业步骤
      # 检出代码
      - uses: actions/checkout@v4

      # 设置 Node.js 环境
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x # 使用 Node.js 版本 20.x

      # 缓存 Yarn 依赖
      - id: yarn-cache
        run: cd projects/market && echo "::set-output name=dir::$(yarn cache dir)" # 设置输出变量以缓存 Yarn 依赖目录

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }} # 缓存 Yarn 依赖目录
          key: yarn-${{ hashFiles('projects/market/package-lock.lock') }} # 缓存键值，根据 yarn.lock 文件生成
          restore-keys: |
            yarn-  # 恢复缓存的键值

      # 安装依赖
      - name: Install submodule
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: cd projects/market && yarn install --frozen-lockfile && cd ../.. # 安装依赖，确保锁定文件一致

      # 编译代码
      - name: Compile
        run: cd projects/market && yarn compile && cd ../.. # 编译代码

      # verify代码
      - name: Verify
        run: cd projects/market && yarn verify base_sepolia && cd ../.. # 编译代码